### ISSUE TITLE
Include data for "Change in 7-day incidence"

### ISSUE THREAD

**Issue by jaimergp** [knudmoeller/berlin_corona_cases#2]
Would you be interested in scraping the incidence trend rate?

![image](https://user-images.githubusercontent.com/2559438/100251140-b5d44f80-2f3e-11eb-8569-dbcb6236fba5.png)

**Comment by knudmoeller** [comment]
Sure, why not? I hadn't even noticed this metric was there. Do you want to have give it a go and submit a PR?

**Comment by knudmoeller** [comment]
I had some time today and added the change in incidence, as you suggested: https://github.com/knudmoeller/berlin_corona_cases#corona-traffic-light-indicators

**Comment by jaimergp** [comment]
Wow, awesome! Thanks! I was going to tackle this next week but yeah, no need now! ❤️

**Comment by knudmoeller** [comment]
No problem, you're welcome! It was just a small thing.
